const ActionTypes = {
	ITEMS_IS_LOADING : 'ITEMS_IS_LOADING',
	ITEMS_HAS_ERRORED : 'ITEMS_HAS_ERRORED',
	ITEMS_FETCH_DATA_SUCCESS : 'ITEMS_FETCH_DATA_SUCCESS',
	ADD_ITEM_SUCCESS : 'ADD_ITEM_SUCCESS',
	CLEAR_ADD_ITEM_SUCCESS : 'CLEAR_ADD_ITEM_SUCCESS',
	ITEM_TO_EDIT : 'ITEM_TO_EDIT',
	REMOVE_ITEM_SUCCESS : 'REMOVE_ITEM_SUCCESS',
	CLEAR_REMOVE_ITEM_SUCCESS : 'CLEAR_REMOVE_ITEM_SUCCESS'
}

export default ActionTypes;


